# Generated by Django 6.0 on 2025-12-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('genres', models.CharField(choices=[('AC', 'Action'), ('FA', 'Fantasy'), ('HO', 'Horror')], max_length=2)),
                ('Age_group', models.CharField(choices=[('AD', 'Adult'), ('CH', 'children'), ('TE', 'Teens')], max_length=2)),
            ],
        ),
    ]
